### ISSUE TITLE
Register Degree Schema

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-framework-dotnet#201]
Upon selecting `Register Degree Schema` in `Issue Credential` the following error is displayed:

![image](https://user-images.githubusercontent.com/7840952/133185785-50b429f8-cd1b-4dd4-8c93-0da3a37b3f59.png)

Prior it was operational.

The command line output shows: 

> web-agent-1_1  | fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
web-agent-1_1  |       An unhandled exception has occurred while executing the request.
web-agent-1_1  | Hyperledger.Indy.InvalidStateException: The SDK library experienced an unexpected internal error.
web-agent-1_1  |    at Hyperledger.Aries.Ledger.DefaultPoolService.GetPoolAsync(String poolName) in /src/src/Hyperledger.Aries/Ledger/DefaultPoolService.cs:line 49
web-agent-1_1  |    at Hyperledger.Aries.Ledger.DefaultPoolService.GetPoolAsync(String poolName, Int32 protocolVersion) in /src/src/Hyperledger.Aries/Ledger/DefaultPoolService.cs:line 38
web-agent-1_1  |    at WebAgent.Controllers.CredentialsController.RegisterSchema() in /src/samples/aspnetcore/Controllers/CredentialsController.cs:line 71
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
web-agent-1_1  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
web-agent-1_1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
web-agent-1_1  |    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
web-agent-1_1  |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
web-agent-1_1  |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
web-agent-1_1  |    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
web-agent-1_1  |    at Hyperledger.Aries.AspNetCore.Age

I am able to connect to agent using qr code.

**Comment by mturetchi** [comment]
probably genesis transaction file is missing

**Comment by dnaicker** [comment]
its definitely something wrong with the indy pool setup, but could not take it further
