### ISSUE TITLE
Cannot run the MediatorAgentService

### ISSUE THREAD

**Issue by airoasis** [hyperledger/aries-framework-dotnet#35]
When I try to run the MediatorAgentService I get the following error

--------------------------------------------------
/aries-framework-dotnet/samples/routing/MediatorAgentService$ dotnet run
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Hyperledger.Aries.AspNetCore.AgentMiddleware Lifetime: Singleton ImplementationType: Hyperledger.Aries.AspNetCore.AgentMiddleware': Unable to resolve service for type 'Microsoft.AspNetCore.Http.RequestDelegate' while attempting to activate 'Hyperledger.Aries.AspNetCore.AgentMiddleware'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Hyperledger.Aries.AspNetCore.AgentMiddleware Lifetime: Singleton ImplementationType: Hyperledger.Aries.AspNetCore.AgentMiddleware': Unable to resolve service for type 'Microsoft.AspNetCore.Http.RequestDelegate' while attempting to activate 'Hyperledger.Aries.AspNetCore.AgentMiddleware'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.RequestDelegate' while attempting to activate 'Hyperledger.Aries.AspNetCore.AgentMiddleware'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MediatorAgentService.Program.Main(String[] args) in /Users/airoasis/Development/dotnet/aries-framework-dotnet/samples/routing/MediatorAgentService/Program.cs:line 16

**Comment by tmarkovski** [comment]
Thanks for finding this. Fixed in #37
