### ISSUE TITLE
Mediator's forward message error

### ISSUE THREAD

**Issue by airoasis** [hyperledger/aries-framework-dotnet#56]
**Context**
I just updated the Nuget package (1.1.1) with the latest update for my Xamarin.Forms project
I also use the latest code for the mediator, and I'm using the Python implemented issuer. 

I didn't have time to look into this issue yet... but I think recent commits related to forward message caused this issue

**Describe the bug**
When the mediator processes the connection message I get the following error message

      Processing message type did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward, {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward", "@id": "0e6f170e-e183-4333-8350-4d1b21514659", "to": "DT75mtm5LSXMzSLcTqFyDebrZRAiG7UwkPeMDKAf7C4S", "msg": "{\"protected\":\"eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJiTmpSN0NmUnNLY2JIUmZ5aWdHWHVXYmcwNXZadWFMVzh0dlVSTTJwSHlMQk9yYVRvRUY5eDc3ZXhZekNUdmtvIiwiaGVhZGVyIjp7ImtpZCI6IkRUNzVtdG01TFNYTXpTTGNUcUZ5RGViclpSQWlHN1V3a1BlTURLQWY3QzRTIiwiaXYiOiJTQ1BQZ0RBMzJSWEQza3pQbFBRRnBQU2VTNXJGZmVnMSIsInNlbmRlciI6Ilk4S2pHNnR3VF9VQlN5eWloZXNOcl9Ma1pQc2wxMXpuWGdWTzhuX3ZsaHNSaVVVd2Y2VDNPVURhRTVOcG5mblNHbjVoLXZvQWtTdktMWjRFRzFCcXl1NWpsZmJzUEZydXBYT0lkdjl3MW9EYmJtWEltMXJPb0gwa002QT0ifX1dfQ==\",\"iv\":\"avRBh4Z8Zcz6m0ZZ\",\"ciphertext\":\"nWsWInvx6M3zY46l1K5UJGpRSY9ujU7Phtr0ckm8fTZl0_LaksHE692FAfIx5iLHloJ_9gsnlA-Efm6VmUnf0vnhUakTvuk9xhO78H0_cR6F1pEs6jez3DMY5hr8JILtWZMAzOs5JvzR3NKBzVg7gzKMfF5A2xpObBhAxy3cRv_ThQi_3SOol8i1cZU8wM47qpNQItNmp3lRoCxwHHB4tyKhVEXoLu7QpFAQJbzw1zImcRdND-PvCCWULLIeCjSzJJT9p_oGJjPxQaSSNJjAyAk4plpHwYo0SZu5laRd9KRts5ijHj5Qd0vH9dLDZYanV01aFWuZlNeKnbm7i98SHYKjzTLt2Ysi1jPfVwTTPe7LiPlt296u-f28kqOh7GWantbJNKMOdASTkbI7UT6HQW57G9YKcKcjpPGBL0TnTuYdx-aiCoZiwcIM6xqryWwfy0pZR0e2KnegURGstr51Sx6-emU5pLNPWN8yzrDYl7C9G2kTQsai_9zPfuOAbOzV2_BmgjddD_dY7ta_o1gG0_0cKjE2ghlYCJTWJzLp0kHiapAzDbEpMj_UhCeBp-rFZdQo50Wk7M5WS8_0bsOuS2yltFMg7rwUzoW936xYYYV_m08kelz-JEjgRXFmxioKiyzhpOVaVD60s9qVryFmoQ6md-HtfD9LsJaa2JBmFsOlbtzk3FH6hOGSwCKvITK_3we8-qTLzoSdvCfHf048Rlrgynll5M7Dvigy3tVPkskmM5tW93Kg27UpeMxiJ4S4O1-z6bj5yBYSWsnIWiA4iKNADRORxTa0GCX9UoHuV_oFT98uHSQ9TX9KKu7FCJfbprkcCNHbtUnf1ccrIxJMrzWQ8lzTDTZvrXnrXWFsBP6mOc2H89AwRW1VxCzagCPRzNuqqQadAJzfpTk2DpS__rYA1tBrAczvhYPQsnqOch8HKBlRMOI6FQywMkWd5mIyGd8GzZtajuxESL2SDMehKd9v3DW-K8dSZizg1rb1OpQk8obQkgjFwiqwKtRSxTIQ0rE4kzruoNvijcb5ZJ2o7LyxoMYu5i3-k0vx8bcGS0TFjaVVW8DBDtCGOkBGgtUS2HAGu-hYnsUDAmjMKwl7pXHz5awsZysnxYbGHaW1UmaUbTf13zIlo2vKUv9Ui5koHrjeRl0ufAMa2yuAd2AA6c_RfDSEMVrB_6WtRmvXLtocsxtJ5T1PJbgkP1xfe-YgTsZnq0p73ORmOui38KUHOWuWlVsr7b-5KyZQh--zQ2yxlXY_tzqzh0wyVKrflh6OUGaCeNO6nwGHsDO9cqAlwKcvtJ8p0kDAoSkY71cmCT1QcsKiigABnGF4lejltAVsOIKFWa6gEnw5-jMtR1EBdh6QW1xMTg-X7KdxtnFN8G_CIVHKhphehM-nL6wefCigsKpj093jT1M8pE40k_PB2_5JztqifbgvPYuzladiH7QOrdBrAMgEEBUgZkWN661p-H6Y-lO8zyfuBEaEb4vj9BjIzuJ66ZP1KxAqDLVj7JlQdsHDC_wecE_E2ibaeUml1qOP_RcxorEMYZqS66NjxVKn6K85_aymY6w6yCbcrfAarWX0KLk6dmE-mNZgeJvA69MYRseT-ofWuh8xVfDZGRg3Bdlv8EMR6AL-aiJLKV0oULEQRrPHs8C-6fn_tUw-lKEbV4ZwUz1c9O89-mJWzif4gMXJSXLJmOBr1K5ZZI3OvaRMFoJeRdZzmJVZyrsFwVmD45otEz9_cbjd0wuA4HQGvOpkvPic4S_Ymr4DTgOc6bgQ13zizeEihAySPx2ZjFHABbTkgW0iJGc2MdATIQyWsk1_fp8=\",\"tag\":\"Rer0ZYozrhdQlUq8Xn7UEQ==\"}"}
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
Newtonsoft.Json.JsonSerializationException: Error setting value to 'Message' on 'Hyperledger.Aries.Features.Routing.ForwardMessage'.
 ---> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JObject'.
   at lambda_method(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Hyperledger.Aries.Agents.AgentMessageReader`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries/Agents/AgentMessageReader.cs:line 30
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonConverter[] converters)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Hyperledger.Aries.Agents.UnpackedMessageContext.GetMessage[T]() in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries/Agents/Models/UnpackedMessageContext.cs:line 86
   at Hyperledger.Aries.Agents.MessageHandlerBase`1.ProcessAsync(IAgentContext agentContext, UnpackedMessageContext messageContext) in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries/Agents/MessageHandlerBase.cs:line 38
   at Hyperledger.Aries.Agents.AgentBase.ProcessMessage(IAgentContext agentContext, MessageContext messageContext) in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries/Agents/AgentBase.cs:line 138
   at Hyperledger.Aries.Agents.AgentBase.ProcessAsync(IAgentContext context, MessageContext messageContext) in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries/Agents/AgentBase.cs:line 112
   at Hyperledger.Aries.AspNetCore.AgentMiddleware.Invoke(HttpContext httpContext, IAgentProvider agentProvider) in /home/did_ict_skt/aries-framework-dotnet/src/Hyperledger.Aries.AspNetCore/AgentMiddleware.cs:line 48
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by airoasis** [comment]
The following commit caused this issue. (Before this commit, it works as expected)
https://github.com/hyperledger/aries-framework-dotnet/commit/302d70bfb2183b036f24b543d2e674f398b1cd03

FYI: The issuer I try to connect is developed with python implemented Aries code.

**Comment by tmarkovski** [comment]
@airoasis Acapy will update their implementation to match this - but they haven't done so, as we're trying to coordinate efforts for pushing this update. If you use the nuget package before that commit, (I believe 1.0.4), things should work.

The reason why we have this incompatibility is discussed in several threads across Aries RFC and it's only a matter of time (few days) until everyone aligns.

**Comment by airoasis** [comment]
I got it. Thanks!!
